### ISSUE TITLE
antigen changes are lost even if antigen-apply

### ISSUE THREAD

**Issue by spider623** [zsh-users/antigen#150]
i have a huge issue with the latest version, older works fine on my other system, every changer i make is lost, it's like it can't write to .zshrc, no idea what to do, no logs since there are no errors, it just doesn't save the changes

**Comment by desyncr** [comment]
Antigen doesn't writes to .zshrc. If you want to persist any changes made on an interactive session you HAVE to manually change .zshrc file.

Please take a look at the [docs](https://github.com/zsh-users/antigen/blob/master/README.mkd#usage).

**Comment by spider623** [comment]
in that case my sincere apologies but then wth there is a save function?

**Comment by desyncr** [comment]
There is no save function. Sounds like a nice addition but I'm not sure how that could be implemented. 
This is because antigen is configured at run-time from any .*rc (ie, .zshrc, .zprofile etc etc) which may contain other configurations, aliases, etc. so we can not just manipulate a rc file at our will.

If you have an idea how that may be implemented please open an issue and let's see how that can be added.
