### ISSUE TITLE
cannot re-`antigen-update` after using `antigen-revert`

### ISSUE THREAD

**Issue by simonbasle** [zsh-users/antigen#162]
Looks like since `antigen-revert` will checkout the various plugins at a specific commit, not a branch, when `antigen-update` tries to pull inside the plugins repos, it cannot find what to pull and one gets a `not on any branch` error message:

```
You are not currently on a branch. Please specify which
branch you want to merge with. See git-pull(1) for details.

    git pull <remote> <branch>

```

**Comment by desyncr** [comment]
`antigen update` should by default checkout `master` branch or the one checked out with `--branch` keyword argument.

This could be achieved with `-antigen-parse-args`, which would return any specified branch name, defaulting in `master` otherwise, then performing a `pull`.

If you need to be locked at certain versions use `snapshot/restore`. This is similar to using a `.lock` file in most package managers.

**Comment by desyncr** [comment]
Done in #212

**Comment by lixiaoyan** [comment]
Seems #311 makes this happened again.

**Comment by desyncr** [comment]
Gonna take a look today. Thanks for reporting.

**Comment by desyncr** [comment]
@lixiaoyan This is fixed in `v2`. Soon to be released.

**Comment by desyncr** [comment]
Fixed in latest release. Closing.
