### ISSUE TITLE
`antigen init` not works on v1.2.3

### ISSUE THREAD

**Issue by VincentBel** [zsh-users/antigen#321]
`antigen init` won't load plugins if cache exists.

## Steps to reproduce

1. open a shell, it doesn't work.(`antigen` has already cache plugins)
2. `antigen reset`, and open a shell again, it works.
3. open a new shell again, it doesn't work.

### Environments

* os version: `macOS Sierra 10.12.1`
* zsh version: `zsh 5.2 (x86_64-apple-darwin16.0)`
* antigen version:  `Antigen v1.2.3`
* my [`zshrc`](https://github.com/VincentBel/dotfiles/blob/master/.zshrc) and [`antigenrc`](https://github.com/VincentBel/dotfiles/blob/master/.antigenrc)

Below is a screenshot of more detail:

![image](https://cloud.githubusercontent.com/assets/6076919/20645765/a5d9817e-b4a2-11e6-8e16-9f3337599930.png)

## More info

* use `source .antigenrc` works
* use `antigen v1.1.0` works, use `antigen v1.2.3` doesn't work
* After adding some logs to antigen source, it seems [`zcache-done` won't call `zcache-load-cache`](https://github.com/zsh-users/antigen/blob/v1.2.3/src/ext/zcache.zsh#L51-L58), which causes the problem.

**Comment by desyncr** [comment]
Thanks for reporting this. I had this issue in mind but I was quite busy lately.

The issue comes from [this check](https://github.com/zsh-users/antigen/blob/develop/bin/antigen.zsh#L1109), which does prevent cache from being loaded when issuing `antigen init`.

A quick fix would be to call `zcache-load-cache` after `zcache-done` on the `init` command.

Scheduled for [v1.2.4](https://github.com/zsh-users/antigen/milestone/13).

**Comment by desyncr** [comment]
Fixed. Check out `develop` or wait until `v1.2.4` is released by next week.

**Comment by VincentBel** [comment]
Thanks for your quick fixing . And `antigen` has came back to life on your great efforts 😉 .

**Comment by desyncr** [comment]
Thanks dude,  your awesome!
