### ISSUE TITLE
How can I have a custom theme without a public Git repo?

### ISSUE THREAD

**Issue by rfgamaral** [zsh-users/antigen#523]
I'm using the agnoster theme with:

```
antigen bundle robbyrussell/oh-my-zsh themes/agnoster.zsh-theme
```

But I'd like to make a small tweak to this theme.

Previously, when I used Oh My Zsh, I could just copy the theme file to `custom/themes`, change it, and pick the "agnoster" theme that my custom one would be used instead.

Anyway to do this with Antigen?

**Comment by desyncr** [comment]
Yes, you can use themes in a local path as follows:

    antigen bundle /path/to/bundle --no-local-clone

In your case you can copy agnoster theme to a local path an bundle it this way:

    antigen bundle /path/to/agnoster-copy agnoster.zsh-theme --no-local-clone

Path must be absolute. Take a look [here](https://github.com/zsh-users/antigen#antigen-bundle) for further details on `antigen-bundle` command.

**Comment by rfgamaral** [comment]
That's it. Thank you :)

**Comment by ferenczy** [comment]
Isn't there any more convenient method to load custom plugins and/or themes, please?

Ideally something like:

    antigen theme theme-name --custom

Actually, it may even be called without the `--custom` argument, since oh-my-zsh is also searching for plugins and themes in the custom directories automatically.

The `bundle` command works, but the semantics that it's a theme is lost, also the absolute path is not very convenient.
