### ISSUE TITLE
Instructions on README do not install the latest version of antigen

### ISSUE THREAD

**Issue by nuno-agostinho** [zsh-users/antigen#524]
The following installation procedure (as detailed in the README file) installs version 1.4.1 of antigen instead of the latest version:

```
curl -L git.io/antigen > antigen.zsh
source antigen.zsh
```

**Comment by desyncr** [comment]
Yes, it's the url for stable version. To get nightly builds use `git.io/antigen-nightly`. See https://github.com/zsh-users/antigen/wiki/Quick-start.

**Comment by nuno-agostinho** [comment]
But is the 2.0.2 version a nightly version? In [GitHub releases](https://github.com/zsh-users/antigen/releases), it shows 2.0.2 as the latest stable version. Also, the README file "markets" the Antigen v2 at the top and then states the instructions (shown in my first comment) to install the 1.4.1 version.

**Comment by desyncr** [comment]
`2.0.2` is the latest released version. Nightly is `develop`. `README.md` in the default branch is from `develop`. See https://github.com/zsh-users/antigen/wiki/Release-process#naming-convention

**Comment by nuno-agostinho** [comment]
@desyncr You are right, but is your default branch `develop`? I never changed to that branch, I thought I was looking into the `master` branch... Sorry for any confusion!

**Comment by desyncr** [comment]
No problem  👍 .

It's the default branch as we always work on `develop`, not `master`. You can configure a default branch but not a default branch only for PR.

**Comment by RuRo** [comment]
Am I correct in my understanding, that `1.4.1` is the latest stable release?
That is none of the following releases are stable:
`2.0.0, 2.0.1, 2.0.2, 2.1.0`

If I am correct, when should I expect the `2.*` versions to become stable (Should I be expecting that at all. No pressure.)? Are the versions not labeled "stable" - unstable? Are they very buggy? I am having a couple of issues in `1.4.1`, that I think `2.*` should fix.

Thank you.

**Comment by desyncr** [comment]
It's fair to ask for stable releases, currently I have no schedule printed down and I'm sorry for that because it's a good way to communicate with end users. I'll create an schedule for stable releases.

I was about to release 2.0.2 as stable last week but I was too busy I could barely work on Antigen.

I'll release 2.1.0 this weekend if no major issues come up.

**Comment by desyncr** [comment]
An answering your questions:  Yes they are unstable and may contain bugs which are fixed in bugfix releases `*.*.x` that come out regularly bi-weekly.

Please note that you're jumping a major version, so you should take a look at the changelog and the release announcement: https://github.com/zsh-users/antigen/releases/tag/v2.0.0

**Comment by desyncr** [comment]
I just released `2.0.2` as stable. `2.1.x` has unresolved issues with prezto modules.
