### ISSUE TITLE
dirname invalid option

### ISSUE THREAD

**Issue by Treggats** [zsh-users/antigen#93]
Hello,
I've been using oh-my-zsh for a while, but after a reinstall it started giving errors. So I decided to give antigen a try.
```
# $HOME/.zshrc
source $HOME/src/dotfiles/antigen/antigen.zsh
# Load oh-my-zsh library
antigen use oh-my-zsh

# Bundles from the default repo (oh-my-zsh)
antigen bundle git
antigen bundle command-not-found

# Python
antigen bundle pip
antigen bundle python
antigen bundle virtualenv
antigen bundle ssh-agent

# Load theme
antigen theme gallifrey

# Syntax highlighting bundle
antigen bundle zsh-users/zsh-syntax-highlighting

# Tell antigen we're done
antigen apply
```
```
# Arch Linux
Linux gaia 3.17.2-1-ARCH #1 SMP PREEMPT Thu Oct 30 20:49:39 CET 2014 x86_64 GNU/Linux
```
When I run it normal, it doesn't complain, but when I want to run tmux I get the following;

![tmux](https://cloud.githubusercontent.com/assets/27585/4896861/25505662-6400-11e4-99af-af01dc76c16e.png)
It complains about the following line;
```
local _ANTIGEN_INSTALL_DIR="$(cd "$(dirname "$0")" && pwd)"
```
After which it runs, but with errors. Is the due to my config or some other reason? I could use some help on this.

**Comment by desyncr** [comment]
It seems as `dirname` is being passed an option flag, something like `-s` or similar. What's the value of "$0"? It should be the antigen.zsh path.

**Comment by Treggats** [comment]
I currently don't have the problem anymore, I've reinstalled my system. Some weird things were going on.
But if I remember correctly, inside tmux $0 said '-zsh' and outside tmux it was 'zsh'

**Comment by sharat87** [comment]
It appears this issue is not seen anymore so I'm closing this issue. Please open a new one if it resurfaces. Thank you!

**Comment by tomsihap** [comment]
I've had this issue many times, even after reinstalling my system... and doing the same mistakes. 
Here's what I've found : 
Here is my .zshrc file. You can see that the path are a mess (mainly because lot of copy-paste without really looking what I was doing by the time). By removing (actually, commenting) the lines that was written twice, I don't have the dirname issue anymore. 

`# Path to your oh-my-zsh installation.
export ZSH=/Users/tomsihap/.oh-my-zsh
export PATH=/usr/local/bin:/usr/local/sbin:$PATH
export PATH=/usr/local/bin:$PATH
export PATH=$(brew --prefix)/bin:$PATH
# export PATH=/Users/tomsihap/anaconda/bin:$PATH
export PATH=~/.composer/vendor/bin:$PATH
export PATH=~/anaconda/bin:$PATH
# export PATH=$PATH:$HOME/anaconda/bin
# export PATH=/Users/tomsihap/anaconda/bin/`
(Oh crap, this looks ugly. TL;DR : this is not an exemple)

**Solution : Clean your path in your .zshrc file and don't just copy/paste what you're told in tutorials but think a little bit more about your own configuration**
